set(CMAKE_SYSTEM_NAME Windows)

set(LLVM_MINGW_DIR "$ENV{LLVM_MINGW_DIR}")

set(CMAKE_C_COMPILER "${LLVM_MINGW_DIR}/bin/clang")
set(CMAKE_CXX_COMPILER "${LLVM_MINGW_DIR}/bin/clang++")

set(TARGET_TRIPLE x86_64-w64-windows-gnu)
set(CMAKE_C_COMPILER_TARGET ${TARGET_TRIPLE})
set(CMAKE_CXX_COMPILER_TARGET ${TARGET_TRIPLE})

set(CMAKE_CXX_FLAGS_INIT "-stdlib=libc++")

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_RC_COMPILER "${LLVM_MINGW_DIR}/bin/x86_64-w64-mingw32-windres")

set(CMAKE_FIND_ROOT_PATH "${LLVM_MINGW_DIR}/x86_64-w64-mingw32")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CPACK_GENERATOR "ZIP")